[project]
name = 'Decentralized-Manufacturing-Additive-Production'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.design-verification]
path = 'contracts/design-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.intellectual-property]
path = 'contracts/intellectual-property.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-certification]
path = 'contracts/material-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.production-tracking]
path = 'contracts/production-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-verification]
path = 'contracts/quality-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
